services:
  - type: web
    name: sistema-orcamento-backend
    env: java
    runtime: "java11"
    plan: free
    branch: main
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/*.jar"
