services:
  - type: web
    name: sistema-orcamento-backend
    env: java
    runtime: java11
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/*.jar"
    plan: free
